### ISSUE TITLE
Skip non electron plugins

### ISSUE THREAD

**Issue by globules-io** [apache/cordova-electron#105]
# Bug Report

## Problem
[ERROR] Error initializing Version Plugin: Missing Command Error

![Capture](https://user-images.githubusercontent.com/13317159/67805461-6edc0800-fa67-11e9-9755-cd03c1f3fb59.PNG)

### What is expected to happen?
Run electron and skip non electron-compatible plugin.

### What does actually happen?
Error popup at start.

## Information
Working android/ios app. Added latest electron platform to test. Added settings.json to have fullscreen browser. Get error popup at start.

### Command or Code
cordova run electron

### Environment, Platform, Device
windows 10 x64

### Version information
cordova-electron@1.1.1
cordova-lib@9.0.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by GedasGa** [comment]
> Added latest electron platform to test.

Hey @globules-io, could you clarify what do you mean by that? Did you update `electron` dependency directly in the `package.json`?

If so, we cannot guarantee compatibility and correctness of the application with other major electron releases other than 4.x.x. We will update the electron version in the next major `cordova-electron` release.

**Comment by globules-io** [comment]
This is a working iOS/Android app. Just added cordova-electron platform to it. When building electron, it does not skip some of my plugins that aren't compatible with it. Not sure how else to say this...

**Comment by GedasGa** [comment]
Could you please share a basic configuration and steps to reproduce this issue? 

Much appreciated!

**Comment by globules-io** [comment]
Here is the config.xml

```
<?xml version='1.0' encoding='utf-8'?>
<widget id="io.globules.ogxelectron" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>HelloCordova</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <platform name="electron">
        <preference name="ElectronSettingsFilePath" value="res/electron/settings.json" />
    </platform>
    <plugin name="cordova-plugin-appversion" spec="^1.0.0" />
</widget>
```

And here is the settings.json

```
{
    "browserWindow": {
        "webviewTag": false,
        "autoHideMenuBar": true
    }
}
```

I just added 1 plugin made for iOS and Android (cordova-plugin-appversion) but I get the error popup at start despite this plugin not compatible with browser or electron

**Comment by globules-io** [comment]
Any update on this? Thanks

**Comment by erisu** [comment]
I do not quite understand the whole scenario but have a couple of recommendation.

1. Remove the `<plugin name="cordova-plugin-appversion" spec="^1.0.0" />` declaration from `config.xml` and place the dependency in `package.json`.

Starting from Cordova CLI 9.x, plugins are no long added to `config.xml`. They are only added and managed in the `package.json` file.

2. I would recommend moving all of the Cordova related packages that are in the `package.json` `dependencies` property and put them in the `devDependencies` property.

Cordova packages such as platforms and plugins are actually dev related packages. When you add them, the necessary files that is needed for the built app will be placed in the necessary locations.

https://github.com/apache/cordova-electron/blob/master/DOCUMENTATION.md#cordova-package-handling

I would recommend trying these two things.

**Comment by globules-io** [comment]
Everything is already set in package.json. This is not the issue.
All dependencies are already set as well.

**Comment by erisu** [comment]
`dependencies` are set as `devDependencies`?

**Comment by globules-io** [comment]
`{
  "devDependencies": {
    "cordova-custom-config": "^5.1.0",
    "cordova-plugin-androidx": "^1.0.2",
    "cordova-plugin-androidx-adapter": "^1.1.0",
    "cordova-plugin-appversion": "^1.0.0",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-network-information": "^2.0.2",
    "cordova-plugin-screen-orientation": "^3.0.2",
    "cordova-plugin-splashscreen": "~5.0.3",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-wkwebview-engine": "^1.2.1",
    "cordova-plugin-wkwebview-file-xhr": "^2.1.2",
    "cordova-plugin-wkwebviewxhrfix": "git+https://github.com/globules-io/cordova-plugin-wkwebviewxhrfix.git",
    "ionic-plugin-keyboard": "~2.2.1",
    "cordova-plugin-whitelist": "^1.3.4",
    "cordova-plugin-inappbrowser": "^3.2.0"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-device": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-network-information": {},
      "cordova-plugin-appversion": {},
      "ionic-plugin-keyboard": {},
      "cordova-plugin-wkwebview-engine": {},
      "cordova-plugin-wkwebview-file-xhr": {},
      "cordova-custom-config": {},
      "cordova-plugin-androidx": {},
      "cordova-plugin-androidx-adapter": {},
      "cordova-plugin-screen-orientation": {},
      "cordova-plugin-wkwebviewxhrfix": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-inappbrowser": {}
    },
    "platforms": [
      "android",
      "ios"
    ]
  },
  "dependencies": {
    "cordova-android": "^8.1.0",
    "es6-promise-plugin": "^4.2.2"
  }
}
`

**Comment by globules-io** [comment]
Now, we created a blank project, added one plugin via the CLI.
Here is the package.json

```
{
  "name": "io.globules.ogxelectron",
  "displayName": "HelloCordova",
  "version": "1.0.0",
  "description": "A sample Apache Cordova application that responds to the deviceready event.",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "ecosystem:cordova"
  ],
  "author": "Apache Cordova Team",
  "license": "Apache-2.0",
  "dependencies": {
    "cordova-electron": "^1.1.1",
    "cordova-plugin-appversion": "^1.0.0"
  },
  "devDependencies": {
    "cordova-plugin-whitelist": "^1.3.4"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-appversion": {}
    },
    "platforms": [
      "electron"
    ]
  }
}
```
This fails

**Comment by erisu** [comment]
```
cordova create electronAppVersionTest
cordova platform add electron

$ cordova platform
Installed platforms:
  electron 1.1.1
Available platforms:
  android ^8.0.0
  browser ^6.0.0
  ios ^5.0.0
  osx ^5.0.0
  windows ^7.0.0

cordova plugin add cordova-plugin-appversion
```

My `package.json`

```
{
  "dependencies": {
  },
  "devDependencies": {
    "cordova-electron": "^1.1.1",
    "cordova-plugin-appversion": "^1.0.0",
    "cordova-plugin-whitelist": "^1.3.4"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-appversion": {}
    },
    "platforms": [
      "electron"
    ]
  }
}
```

I run the electron project:

```
cordova run electron --nobuild
```

I have just confirmed the error you are seeing.

I took a closer look at the plugin's source code and see that the developers has defined the clobbering of the JS file outside of the platform scope. This means it will clobber the JS file for all platforms including the non-supported platforms.

They should update the plugin code to only clobber the JS file the supported platforms, or update the JS code to check as well if the platform it is being executed on is one of the supported platforms.

https://github.com/Rareloop/cordova-plugin-app-version/blob/master/plugin.xml#L7-L9

Cordova Electron is not the culprit in this error.

**Comment by globules-io** [comment]
We've just tried with another plugin
`cordova-plugin-splashscreen` which does not support electron. The app crashes as it is not skipped.
Is this related to that plugin as well?

**Comment by erisu** [comment]
The `cordova-plugin-splashscreen` also clobbers to every platform but in this case it supports the `browser` platform which is a valid fallback platform for the `electron` platform.

The error you are showing above is something I do not see on a blank project.

This is what I see when I run the app:

**Splash Screen**
<img width="912" alt="electron-splashscreen" src="https://user-images.githubusercontent.com/1029107/72772884-97c7ff80-3c48-11ea-99a6-0d6b5314b844.png">

**After Splash Screen**
<img width="912" alt="electron-after-splashscreen" src="https://user-images.githubusercontent.com/1029107/72772908-ab736600-3c48-11ea-81d6-bf1a6b19e52a.png">

**Comment by globules-io** [comment]
Well, it happens here... So basically what I understand is that some or most of the plugins aren't programmed properly which has an effect over the electron build, which in a way, renders that platform sort of non functional, right?

**Comment by globules-io** [comment]
https://ibb.co/cJdZGJR

**Comment by erisu** [comment]
The three error I got were

> Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'". Either the 'unsafe-inline' keyword,... or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
> 
> Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'". Either the 'unsafe-inline' keyword,... or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
> 
> Failed to load resource: net::ERR_FILE_NOT_FOUND

First two errors I would need to update the `Content Security Policy` and the third error is that it failed to load is the missing logo.png which I can add.

The warning is also:


> Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.


And as for your comment/question:

> some or most of the plugins aren't programmed properly which has an effect over the electron build, which in a way, renders that platform sort of non functional

I wouldn't pinpoint this issue directly to the Electron platform.

In this case, it is the plugin that is causing the application to have errors. 

The app version plugin specifically does not properly clobber the JS file only to support platforms. Or optionally, it does not check in the JS file that the platform is a supported platform before attempting to execute its code.

If you take the same plugin (`cordova-plugin-appversion`) but build/run for the `osx` platform, it also crashes because of the app version plugin still tries to execute.

What I can confirm is that there are some plugins that aren't programmed properly which can have an effect over ANY platform and introduce issues.

```
2020-01-21 12:41:57.202 macOSAppVersion[24386:4190294] WebStoragePath is '/Users/foobar/Library/Application Support/com.foobar.macOSAppVersion', modify in config.xml.
2020-01-21 12:41:57.739 macOSAppVersion[24386:4190294] ERROR: Plugin 'RareloopAppVersion' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2020-01-21 12:42:02.670 macOSAppVersion[24386:4190294] deviceready has not fired after 5 seconds.
2020-01-21 12:42:02.670 macOSAppVersion[24386:4190294] Channel not fired: onCordovaAppVersionReady
```

**Comment by globules-io** [comment]
I gotcha for the appversion one but I mean the splashscreen too. Ok I'm gonna close this issue but afaic, due to the plugins issue, I will have to build a separate version just for electron and remove plugins. Thanks for your time.
