### ISSUE TITLE
Update to latest electron-builder (macOS Catalina support)

### ISSUE THREAD

**Issue by buu700** [apache/cordova-electron#107]
# Feature Request

## Motivation Behind Feature

Building for Windows from the latest macOS with cordova-electron fails.

However, as of [v21.1.1](https://github.com/electron-userland/electron-builder/releases/tag/v21.1.0), it seems that electron-builder adds supports for this (via Parallels).

## Feature Description

Update electron-builder from `^20.38.4` to the latest version.

**Comment by erisu** [comment]
I am closing this ticket out as the master branch contains the latest release of `electron-builder`.

https://github.com/apache/cordova-electron/blob/751b80a09a85c5ae6786006297845ac07542371c/package.json#L28

The ETA for next release has not be finalized or determined.
