### ISSUE TITLE
MacOS permission denied darwin-X64

### ISSUE THREAD

**Issue by globules-io** [apache/cordova-electron#115]
# Bug Report

## Problem
`sudo cordova run electon`

### What does actually happen?
```
Downloading tmp-6315-0-electron-v4.2.12-darwin-x64.zip
Error: EACCES: permission denied, open '/Users/eric/Library/Caches/electron/tmp-6315-0-electron-v4.2.12-darwin-x64.zip
```

### Environment, Platform, Device
MacOSX 10.15.1
Cordova@9
cordova-electron@1.1.1
electron@7.1.1 (global install)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by erisu** [comment]
I am unable to reproduce this issue.

I noticed that you are using `sudo` when executing the `cordova` command. 
It is not recommended to use `sudo`. You may need to reinstall cordova without `sudo` and try again.

Also, I noticed some of the tooling is outdated. I would recommend upgrading everything if possible.

* `cordova@10.0.0`
* `cordova-electron@3.0.0`
  * This comes with `electron@14.0.0`

**Comment by globules-io** [comment]
This has been opened more than 2 years ago...
