### ISSUE TITLE
App cannot be build due to an error parsing the dependencies of the package.json file

### ISSUE THREAD

**Issue by dec** [apache/cordova-electron#130]
# Bug Report

## Problem

The app cannot build properly due to an error, apparently, when process the "package.json" file.

### What is expected to happen?

The app must be successfully build, even if there are some nodejs / electron modules dependencies.

### What does actually happen?

When the app starts to build, a "package.json" file is prepared with lot of modules inside the "dependencies" key of the JSON file. 

For simplification, below is a "package.json" which only contains one dependency, however, even with this one, the app cannot be build properly.

```
{
  "requires": true,
  "lockfileVersion": 1,
  "dependencies": {
    "7zip-bin": {
      "version": "4.1.0",
      "resolved": "https://registry.npmjs.org/7zip-bin/-/7zip-bin-4.1.0.tgz",
      "integrity": "sha512-AsnBZN3a8/JcNt+KPkGGODaA4c7l3W5+WpeKgGSbstSLxqWtTXqd1ieJGBQ8IFCtRg8DmmKUcSkIkUc0A4p3YA=="
    }
  }
}
```

The first line of the error than appear (sorry, I try, but can't insert here more error output without break the apparence of the post dramatically...) is the below one:

>node_modules.Dependency.Dependencies: ReadString: expects " or n, but found {, error found in #10 byte of ...|ip-bin

If we manually remove the dependencies, that is, if we prepare the "package.json" file like below:

```
{
  "requires": true,
  "lockfileVersion": 1,
  "dependencies": {}
}
```

Then the app build successfully, however, I think the dependencies means "node/electron modules ready to be used", and, certainly, we want to use some of these modules... so can't simply remove the dependencies from the "package.json" file.

## Information

I am not sure if this problem is just for me... I try updating node js, use the latest Cordova version and the latest Cordova Electron version too.

### Command or Code

In fact I always can reproduce the problem, however, as I mentioned above, I am not sure if this problem is just for me or what... :-(

### Environment, Platform, Device

I try to compile the app in Windows 10 64 bits.

### Version information

Cordova version: 9.0.0

Cordova Electron version: 1.1.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above (I hope! But please, ask me for anything else!)

**Comment by dec** [comment]
Hello to all,

I am not sure if the above issue is related with a first one which occur when I try to build the app using cordova electron. This first issue is related with the "package.json" file which cordova electron generates. The error is "ENON: can't found package.json", but there is "package-lock.json" file.

So what I do is to rename such "package-lock.json" file to "package.json". I think this is wrong... because the "package-lock.json" contents are not what are expected in "package.json".

The "package-lock.json" dependencies are defined in the below way:

`  "dependencies": {
    "7zip-bin": {
      "version": "4.1.0",
      "resolved": "https://registry.npmjs.org/7zip-bin/-/7zip-bin-4.1.0.tgz",
      "integrity": "sha512-AsnBZN3a8/JcNt+KPkGGODaA4c7l3W5+WpeKgGSbstSLxqWtTXqd1ieJGBQ8IFCtRg8DmmKUcSkIkUc0A4p3YA=="
    },`

And that causes the error that I described above. However, if I change the dependencies like below:

`  "dependencies": {
    "7zip-bin": "4.1.0"
  }`

That's works, that is, there is no error when read the "package.json". If I am right, then the main problem to me is the "ENON: can't found package.json". I try to simply rename the "package-lock.json" to "package.json", but, probably this is not the way in which I must solve the "ENON" error.

Anyone can help no this question? I search around the "ENON" problem but I can't find information related with cordova electron. Probably it's a problem only to me, because, I think a problem like that must be reported by several people, and, apparently it's not the case.

**Comment by breautek** [comment]
You can use triple ` (backtick) key to open and close preformatted blocks, or you can upload a log file of the output. 

You can't just rename package-lock.json to package.json, they are two completely different files for two completely different purposes, and therefore have two completely different structures.

If you want to reinstall all your dependencies from scratch, You can try deleting `package-lock.json` and `node_modules` folder, then running `npm install` again. This will create a new `package-lock.json` file will be generated, but some dependencies, including sub dependencies may be updated to their latest satisfactory versions (as defined in `package.json`).

**Comment by dec** [comment]
Hello to all,

Thanks @breautek for your help. Yes; definetively I am confusing with "package-lock.json" and "package.json": I understand now (thanks for your words too) that there are completely different files.

So the problem is the first one issue... that is... this error:

```
ENOENT: no such file or directory, open 'C:\Users\dec\Desktop\NewAppdab\compiled\package.json'
```

Can I ask if a "package.json" file is expected to be created by Cordova Electron? Or may it's our duty to prepare that file?

**Comment by dec** [comment]
Hello to all,

Here is the complete log for the build / error:

```
Using cordova-fetch for cordova-electron@1.1.1
Adding electron project...
Creating Cordova project for cordova-electron:
        Path: C:\Users\dec\Desktop\MyApp\compiled\platforms\electron
        Name: New App 1
ENOENT: no such file or directory, open 'C:\Users\dec\Desktop\MyApp\compiled\package.json'
ENOENT: no such file or directory, open 'C:\Users\dec\Desktop\MyApp\compiled\package.json'
```
I get that after apparently Cordova Electron download all the modules, etc. Certainly the file which is refer in the error do not exists, so, I am not sure if the problem is that Cordova Electron can't create that file... or if that file must be created by me (I think not, because it's not mentioned in the documentation).

**Comment by erisu** [comment]
From reading the complete log that you provided, I am suspecting that your project's root directory is `C:\Users\dec\Desktop\MyApp\compiled` because the `platforms` directory resides in the root directory of a Cordova project. 

Based on that given information, the `package.json` file that it is trying to find is your project's `package.json`. This file is normally created when you create the Cordova project, not when you add the Cordova Electron platform to the project.

I suspect you created the project with the command `cordova create compiled` which would create the folder `compiled` with the file `package.json`, among other files.

**Comment by dec** [comment]
Hello to all,

Thanks for your help @erisu. Certainly the "compiled" directory is the root directory of the Cordova project. Then in that folder we can see the "platforms" directory, the "node_modules", etc.

The above "platforms" and "node_modules" folders are created once I run the below commands in the "compiled" directory:

```
REM Add the Electron platform for our app
CALL cordova platform add electron

REM Debug our app for the Electron platform
CALL cordova build electron
```

So... maybe I am missing something? I means... I am using certain tool which prepares some Apache Cordova stuff like the config.xml file, etc. So, I am not sure if that tool (I am the developer of that tool) must create a "package.json" file...

Or maybe before the command "cordova platform add electron" we need to execute a previous command like "create"?

**Comment by dec** [comment]
Hello to all,

Ok! So finally I know what is happen here. Thanks you guys, because without your help I never reach this. What happen is that in my scenario I never uses the "cordova create" command.

I just run that command and see that Apache Cordova creates a "package.json" file...

It's just like that. The tool that I am using do not create any "package.json" file, so, the file is missing.

I am curious now... because the this tool that I use prepares all the required stuff for Cordova, that is, the "config.xml" file, resources, etc., and, I can compile apps for the Android and the iOS platform without any problem, that is, without problems with the "package.json" file...

So... if I am not wrong, this "package.json" must be present (like the "config.xml" file) for the Cordova Electron platform...

I am correct?

**Comment by erisu** [comment]
This is the typical the commands one would use to create a project.

> npm install -g cordova@latest
> cordova create helloworld
> cd helloworld
> cordova platform add electron@latest

* First command will install the latest Cordova CLI globally using NPM.
* Second commands creates the project. In your cause you would replace `helloworld` with `compiled.`
* Third command to go into your new project
* Forth command to add the latest Cordova Electron platform.

The second command should create the project with all the base files for example `config.xml`, `package.json`, and among others.

If you don't have the `package.json` in the project root directory next to your `config.xml` then there is something wrong with the project creation. What version of Cordova CLI are you using?

**Comment by dec** [comment]
Hello to all,

Thanks for your fast help @erisu. I am very embarrassed... the problem is not with Apache Cordova nor Cordova Electron: the problem is the tool that I am using, which, never creates the "package.json" file. This tool creates the "config.xml" among other required files, but, not a "package.json" file.

So I am working now in order to create that file.

However, something maybe curious... is that apparently the "package.json" file is not required to build an app for the Android platform, nor the iOS platform, since I use the referred tool without problems to get apps on these platforms.

The point is that, apparently, Cordova Electron requires that "package.json" file, so, certainly expect it, and, I never provide it.

So no matter the CLI version, @erisu, since Apache Cordova nor Cordova Electron is the problem here: once a "package.json" file everything works as expected. (Well, not all... in fact... but there are completely different issues than this one).

So thanks to all for your help, specially to @erisu, which point me in the right direction, once I understand that "package.json" is certainly created by Apache Cordova, but, with the "create" command, which I am not using.

P.S. I am not sure if this issue must be closed... or how I can do it... but certainly this is not an issue of Apache Cordova nor Cordova Electron, but the tool that I am using. Thanks again for your help!

**Comment by erisu** [comment]
The reason why Cordova Electron build, specifically the prepare step, needs the `package.json` is because it fetches the list of defined `dependencies` to copy them inside the Electron's `package.json`.

It is done this way so you can have NPM dependencies available for your Electron project. This process does not exist in iOS or Android as they can not use NPM packages.

**Comment by erisu** [comment]
I will go ahead and close out this ticket since this is not a bug.

**Comment by dec** [comment]
Hello to all,

So thanks again @erisu. Now it's clear why Android nor iOS platforms requires that "package.json" file. and you point me in the right direction again: I need to study the "package.json" file contents, since it's the way to set the possible app NPM dependencies.

Thanks again for your great help @erisu!
