### ISSUE TITLE
Can not import native nodejs modules

### ISSUE THREAD

**Issue by zorn-v** [apache/cordova-electron#133]
#  Problem
You can not use `const { app } = require('electron')` or `const fs = require('fs')` in plugins because `require` is overriden

**Comment by erisu** [comment]
Did you try this?

https://github.com/apache/cordova-electron/blob/master/DOCUMENTATION.md#how-to-support-nodejs-and-electron-apis

**Comment by zorn-v** [comment]
Yep. Try this https://github.com/apache/cordova-plugin-file/pull/371 :wink: 
You will get this https://github.com/apache/cordova-electron/blob/master/cordova-lib/cordova.js#L53

`require` is overriden by cordova-electron GLOBAL var.

**Comment by erisu** [comment]
What about following this comment: https://github.com/apache/cordova-js/pull/210#issuecomment-515670824

**Comment by zorn-v** [comment]
Hmm... I though about it but not test it

**Comment by zorn-v** [comment]
`global.require` returns object like this
![изображение](https://user-images.githubusercontent.com/12619075/72678104-6f2bf280-3aee-11ea-9edb-f71f4d6f0638.png)

So I need to dig deeper )
