### ISSUE TITLE
Can't pass gatekeeperAssess and other valid config options, through to electron-builder

### ISSUE THREAD

**Issue by WesUnwin** [apache/cordova-electron#139]
# Bug Report

### What is expected to happen?

User should be able to pass through gatekeeperAssess: false, as well as any abitrary, valid electron-config option (as per: https://www.electron.build/configuration/mac).

### What does actually happen?

electron-builder build() function does not receive options such as gatekeeperAssess.

## Information
Likely a problem with this file picking what options to pass through:

https://github.com/apache/cordova-electron/blob/ee24d80df57e5578d2081318e9e7eb4e849d61a4/bin/templates/cordova/lib/build.js

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by WesUnwin** [comment]
Hopefully i'm correct about this and there is not some other way of passing things through - need urgent help!

**Comment by breautek** [comment]
You're not going to get "urgent" help on an open source project backed by volunteers contributing on their own free time. Nobody is on payroll here and spamming the github issues asking for urgent or immediate help is not going to make a solution appear faster. So please stop spamming.

We see your issue report (and we appreciate that you followed the issue form :+1: ). Now you have two choices:
1. Wait for someone who is knowledgeable on the electron platform to provide guidance or to fix the problem. Unfortunately I'm not a mac user, nor do I have any electron experience, so I'm not your guy here.
2. Tackle the problem yourself, and if you do find a solution, then PRs are welcome. At the very least, you'll likely learn something about the code base.

**Comment by AnnetaCollins** [comment]
So the gentleman submits what appears to be an accurate account of a limitation (although not sure a bug) that likely many in the community and myself are interested in quickly dealing with, and took the right channel to report it - don't see how this is "spam". You won't get many contributions btw treating others like that :(

One workaround I've personally considered is just code signing and notarizing the app externally to cordova. I believe you can disable code signing by removing the identify from the config, then use xcode related tools, although a little more challenging. Hope this helps!

**Comment by breautek** [comment]
> So the gentleman submits what appears to be an accurate account of a limitation (although not sure a bug) that likely many in the community and myself are interested in quickly dealing with, and took the right channel to report it - don't see how this is "spam". You won't get many contributions btw treating others like that :(

Not trying to be rude. I may appear so here but you're missing context. He was also posting on other issues demanding immediate assistance.

**Comment by erisu** [comment]
I have already looked into notarization and have a possible implementation solution, which I tested locally and seems promising. 

As for PR, it is not yet prepared or ready to be submitted.

The master branch has already been bumped for the next major items and also currently working on a refactor which I want to complete before I submit a PR for the notarization.

All in all, I am not expecting something to be prepare or release in 1.x and would be in the next major.

(ETA for next major is also not available as there are a lot of other repos that need to be finished as well.)

**Comment by WesUnwin** [comment]
thanks

> > So the gentleman submits what appears to be an accurate account of a limitation (although not sure a bug) that likely many in the community and myself are interested in quickly dealing with, and took the right channel to report it - don't see how this is "spam". You won't get many contributions btw treating others like that :(
> 
> Not trying to be rude. I may appear so here but you're missing context. He was also posting on other issues demanding immediate assistance.
> 
> > One workaround I've personally considered is just code signing and notarizing the app externally to cordova. I believe you can disable code signing by removing the identify from the config, then use xcode related tools, although a little more challenging. Hope this helps!
> 
> Thank you for sharing your workaround.

No one is "demanding" anything from anyone including yourself, I was asking for help and contributing myself by pointing out a possible solution via passing through values to electron-builder. It seems we could allow passing all values in build.js which may be useful for other things too. Many people including myself are willing to help btw regardless of whether we're on payroll or not, so not sure why you mentioned that. If interested, I could open a PR to pass through some of these values, but It may be worth me asking in advance, or working around this till the below mentioned work in progress is available.

**Comment by WesUnwin** [comment]
thanks @erisu that sounds great!
