### ISSUE TITLE
Support newest Chrome/Electron

### ISSUE THREAD

**Issue by Markus-Ende** [apache/cordova-electron#150]
# Feature Request

## Motivation Behind Feature
In the officially published npm package (v1.1.1) currently Electron 4 with Chrome 68 is used, which is outdated.

## Feature Description
In my project, I need a newer version of Chrome to support all functionalities. Chrome 68 is also very outdated from a security perspective. Would it be possible to update the electron dependency to a newer version for v1.1.1, like you did in the master branch?

## Alternatives or Workarounds
Provide a way to force using newest Chrome version.

**Comment by erisu** [comment]
The master branch has already been updated with the latest release.

```
"electron": "^8.2.5",
```

There is a chance that `9.0.0` will be released within this month and will be upgraded once released. This is all for the preparation of Cordova Electron Platform's next major release.

Thank for you the ticket, but I will go ahead and close it out as we have been pushing updates and working for the next major release.

There is currently no hard given ETA for the next major release but we are working on it.
