### ISSUE TITLE
build.json file missing

### ISSUE THREAD

**Issue by lofilips** [apache/cordova-electron#161]
Hi, I'm following this guide https://cordova.apache.org/docs/en/latest/guide/platforms/electron/#build-configurations to customize build configurations and it talks about build.json file that should be located in the project's root directory. This is my project directory after running `cordova platform add electron`:

<img width="1440" alt="Schermata 2020-07-18 alle 02 31 10" src="https://user-images.githubusercontent.com/50113365/87840523-6602bf00-c8a0-11ea-98ad-0d342028a26d.png">

I don't have that file and I don't know where to set build configurations. What could be the problem?

**Comment by erisu** [comment]
This file is something you are suppose to manually create on your own. This has always been the process for configuring Cordova projects build settings. For example signing. This file is not something that gets created when adding any platform.
