### ISSUE TITLE
app.getVersion() is invalid

### ISSUE THREAD

**Issue by zdm** [apache/cordova-electron#163]
# Bug Report

## Problem
app. getVersion() returns electron package version instead of version from app package.json.

### What is expected to happen?
Expected to get version string from app package.json.

### What does actually happen?
Actually I get version from electron package.json.

## Information

```
const app = electron.app || electron.remote.app;
console.log(app.getVersion());
```
### Version information

Windows 10

## Checklist

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by ComexioDev** [comment]
I have the same problem, but only if i am running my app with "cordova run electron --nobuild".
Try building the app, run the app itself (platform/electron/build/yourplatform-unpacked/yourapp) and test it again.

**Comment by zdm** [comment]
I need to get correct version when run with --nobuild.
I don;t need to build it every time, this is long.
Do you know, how to achieve this?

**Comment by ComexioDev** [comment]
I dont know how to achieve this. I can only tell you, that it works in a release build.

Maybe you could do something hacky like:

`const appVersion = <yourAppVersion>;
const electronVersion = <yourElectronVersion>;
let version = app. getVersion();
if(version === electronVersion){version = appVersion;}`
Then use `version` in your Code instead of ` app. getVersion()`

**Comment by zdm** [comment]
It works incorrectly when running with `cordova run` command, no matter with `--no build` option or without.

**Comment by zdm** [comment]
```
        var version;

        // devel mode
        if ( app.getName() === "Electron" ) {
            version = window.require( "../../../package.json" ).version;
        }

        // production mode
        else {
            version = app.getVersion();
        }
```
I will close this issue, because it is not directly related to the cordova-electron.
