### ISSUE TITLE
Builds fail on macOS 12.3 (Monterey)

### ISSUE THREAD

**Issue by noe2505** [apache/cordova-electron#220]
# Bug Report

Cordova Electron builds fail on macOS 12.3

Apple has removed support for python2, the version of electron-builder that is required by cordova-electron depends on python2 to work.

## Problem

As follows, notice last line:

user@N0-2 myApp % cordova build electron      
  • electron-builder  version=22.14.13 os=21.4.0
  • writing effective config  file=platforms/electron/build/builder-effective-config.yaml
  • installing production dependencies  platform=darwin arch=x64 appDir=/Users/user/Sites/myApp/platforms/electron/www
  • packaging       platform=darwin arch=x64 electron=14.0.0 appOutDir=platforms/electron/build/mac
  • signing         file=platforms/electron/build/mac/myApp.app identityName=Developer ID Application: Dev Name (DevID) identityHash=hash provisioningProfile=profile.profile
  • building        target=DMG arch=x64 file=platforms/electron/build/myApp-0.1.7.dmg
  • building        target=macOS zip arch=x64 file=platforms/electron/build/myApp-0.1.7-mac.zip
  • building block map  blockMapFile=platforms/electron/build/myApp-0.1.7-mac.zip.blockmap
**Exit code: ENOENT. spawn /usr/bin/python ENOENT**

### What is expected to happen?

cordova build electron     should run without issue

### What does actually happen?

Build process interrupted with:

**Exit code: ENOENT. spawn /usr/bin/python ENOENT**

### Command or Code

cordova build electron

### Environment, Platform, Device

MacOS 12.3 Monterey (released on early 2022)

### Version information

Cordova: 11.0.0
cordova-electron: 3.0.0

This error is not dependant on any plugins.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment]
Crossref to the electron-builder issue: https://github.com/electron-userland/electron-builder/issues/6606

**Comment by noe2505** [comment]
I guess it is true that Cordova is dead... two months on, zero action on this critical issue.
