### ISSUE TITLE
Error launching app

### ISSUE THREAD

**Issue by Polm90** [apache/cordova-electron#34]
# Bug Report

## Problem
When launching the app with the command cordova run cordova-electron --no-build i receive the following error: "Unable to find Electron app"
![tempsnip](https://user-images.githubusercontent.com/4883463/53563932-d4cd6400-3b55-11e9-98e1-b91d30ac176c.png).

I'm using Windows 10 with cordova 8.1.2 (cordova-electron 1.0.0)

**Comment by janpio** [comment]
Did you build the app before?

**Comment by erisu** [comment]
Sorry, please wait for the 1.0.1 patch release that I will prepare and push out hopeful Monday next week.

There was a missed PR that would allow Electron to work with pre-Cordova CLI 9.x. 

This PR is already merged into master. https://github.com/apache/cordova-electron/pull/33

The release originally was targeted for Cordova CLI 9.x only and tested against nightly. The decision to add pre-9 was a post decision.

Sorry for the confusion.

**Comment by erisu** [comment]
@janpio For Electron, it is not required to build when calling `cordova run`. The run command spools a prebuilt Electron process and loads the app. The built app from run, if the flag is not set, is not used.

This allows faster previewing and testing with out waiting though an entire build process.

**Comment by erisu** [comment]
`cordova-electron@1.0.1` has been released with the fix to support Cordova 8.x.

**Comment by Polm90** [comment]
I'm still getting the same error.
I'm removed the old version and installed the old one

**Comment by erisu** [comment]
@Polm90 Can you provide exact commands?

For example are you running these commands?
```
cordova create projectDirName
cd projectDirName
cordova plarform add cordova-electron@latest
cordova run cordova-electron --nobuild
```

**Comment by Polm90** [comment]
Yes: exactly them. I've tried with exatcly all your commands

**Comment by GedasGa** [comment]
It seems that the commit that fixes this error is missing in the release. However, what you could do now, for testing purposes, is to try and change the `module.exports.run` in the `<project-dir>/platforms/cordova-electron/cordova/lib/run.js` file.

From this:

```
module.exports.run = (args) => {
    const child = proc.spawn(electron, ['./platforms/electron/www/main.js']);

    child.on('close', (code) => {
        process.exit(code);
    });
};
```

To this:
```
module.exports.run = (args) => {
    const pathToMain = path.resolve(__dirname, '..', '..', 'www', 'main.js');
    const child = proc.spawn(electron, [pathToMain]);

    child.on('close', (code) => {
        process.exit(code);
    });
};
```

**Comment by Polm90** [comment]
With this fix now it works!

**Comment by erisu** [comment]
@Polm90 `cordova-electron@1.0.2` has been released and should contain the fix. Can you please try this released version?
