### ISSUE TITLE
Installer icon is not set when using a custom build configuration

### ISSUE THREAD

**Issue by GedasGa** [apache/cordova-electron#44]
# Bug Report

### What is expected to happen?

Installer icon is set in the `{project_root}/platforms/electron/build/builder-effective-config.yaml` file when using a custom build configuration.

### What does actually happen?

Installer icon is noot in the `{project_root}/platforms/electron/build/builder-effective-config.yaml` file, using default Electron icon.

### Command or Code

Using custom build configuration`{project_root}/build.json`:
```
{
  "electron": {
    "mac": {
      "package": [
        "tar.gz",
        "dmg",
        "zip"
      ],
      "arch": ["x64"]
    }
  }
}
```

Then building the application.
```
cordova build electron
```

### Environment, Platform, Device

All platforms. 

### Version information

Codova v9.0.0 and Electron v1.0.2

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by ttencate** [comment]
I just ran into this issue, thank you @GedasGa for the fix!

However, I can't seem to figure out how to use it, which may or may not be related to the fix itself. I tried:

    cordova platform update 'electron@git://github.com/apache/cordova-electron.git#f0b9f8d749a2c17a6ce025a859ae595921df0160' --save

This updates `package.json` correctly. But it seems to have no effect on either the generated `builder-effective-config.yaml`, or the "default Electron icon is used reason=application icon is not set" warning.

If I remove my `build.json`, an `icon: installer.png` line does appear in  `builder-effective-config.yaml`, so I'm pretty sure that the icon is configured correctly in `config.xml`.

Am I missing something?

**Comment by GedasGa** [comment]
Did you try to remove the existing platform folder? My guess is that you actually don't have the changes. When you run just `cordova platform update`, it updates `cordova-electron` package in the `node_modules` folder. However, if you still have `platforms/electron` folder, it remained unchanged.

Try this:
```
cordova platform rm electron
cordova platform update 'electron@git://github.com/apache/cordova-electron.git#f0b9f8d749a2c17a6ce025a859ae595921df0160' --save
cordova platform add electron
```

**Comment by ttencate** [comment]
Thank you, that worked!

As you may have guessed, I'm new to Cordova. Updating the platform before it's even added is rather counterintuitive to me. The [official docs](https://cordova.apache.org/docs/en/9.x/platform_plugin_versioning_ref/index.html#updating--removing-platforms) don't suggest that `cordova platform update` requires any additional steps. Maybe `cordova prepare` would also have worked?

Maybe it's just me, but if you also think the docs could be improved, I'll file an issue.

**Comment by GedasGa** [comment]
Yeah, that would also work. However, first, you would have to delete the `platfroms/electron` folder and just then run the `cordova prepare` command.

It mentions something, but of course, it could be clearer. We're planning to do a major docs update.

**Comment by Polm90** [comment]
I'm still having the issue with cordova-electron 3.1.0 and cordova 11.0.0.

How can I solve this issue?
