### ISSUE TITLE
Docs: Add Electron to list of supported platforms (and remove old ones)

### ISSUE THREAD

**Issue by janpio** [apache/cordova-electron#49]
https://cordova.apache.org/docs/en/latest/reference/cordova-cli/index.html#supported-platforms

1. Add "Electron" to the list of supported platforms.
2. When at it, please also remove Blackberry10 and Ubuntu.
3. Remove the "Deprecated Platforms" completely.

**Comment by erisu** [comment]
Reopening as task was not completed.

**Comment by macskay** [comment]
What needs to be done here still?
