### ISSUE TITLE
Can't change a default application category for Linux targets

### ISSUE THREAD

**Issue by GedasGa** [apache/cordova-electron#56]
# Feature Request

## Motivation Behind Feature

There is no way to change an application category for Linux targets. It will always be set to a default value - "Utility". 

Output in the terminal, when building for a Linux target:
```
  • application Linux category is set to default "Utility" reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
```

## Feature Description

Allow user to set the application `category` in the `build.json` file.

For instance, like this:
```
{
  "electron": {
    "linux": {
      "package": [
        "tar.gz"
      ],
      "arch": ["x64"],
      "category": "Game"
    }
  }
}
```

**Comment by bksubhuti** [comment]
I have this problem.. what was the solution?

**Comment by mazm786** [comment]
> # Feature Request
> ## Motivation Behind Feature
> There is no way to change an application category for Linux targets. It will always be set to a default value - "Utility".
> 
> Output in the terminal, when building for a Linux target:
> 
> ```
>   • application Linux category is set to default "Utility" reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
> ```
> 
> ## Feature Description
> Allow user to set the application `category` in the `build.json` file.
> 
> For instance, like this:
> 
> ```
> {
>   "electron": {
>     "linux": {
>       "package": [
>         "tar.gz"
>       ],
>       "arch": ["x64"],
>       "category": "Game"
>     }
>   }
> }
> ```

I want to change default electron icon for linux build. Please post solution.

**Comment by Grijan** [comment]
were you able to change the default icon?

**Comment by zhangshuaiqi** [comment]
在项目中创建icon 文件夹，复制图片到文件夹，修改图片属性 ‘如果较新则复制’。。一定要加  bin
 "build": {
    ..........
    "linux": {
      "icon": "bin/icon/ddd.png"
    },
    "win": {
      "icon": "bin/icon/ddd.png"
    },
  }

**Comment by Grijan** [comment]
thanks @zhangshuaiqi but I don't think this is the proper way to change the icon for LINUX, for windows this works but for Linux there is a different approach.
