### ISSUE TITLE
GPS Location does not work with electron 4.x on Windows

### ISSUE THREAD

**Issue by NisStrom** [apache/cordova-electron#64]
# Bug Report

## Problem
GPS Location does not work
### What is expected to happen?
Using navigator.geolocation.getCurrentPosition() or navigator.geolocation.watchPosition() does work as intendent.

### What does actually happen?
The first call return a PositionError, all calls after that do not return anything and result in a timeout.

This issue is know to electron and is fixed in electron 5.x but is not going to be fixed for electron 

An updgrade to electron 5.x would therefore be needed.

**Comment by erisu** [comment]
This issue had been resolved on Sept. 2019 when the Electron dependency was bumped and merged.

The current release of Cordova Electron, v2.0.0, is using Electron 10.1.2.

I have tested and confirmed that I am able to fetch the current position with `navigator.geolocation.getCurrentPosition()`.

_Note: It is still required to have a proper API key and billing configiration with Google API._
