### ISSUE TITLE
Possibility to customize exe name

### ISSUE THREAD

**Issue by Polm90** [apache/cordova-electron#72]
Is it possibile to customize the exe name?

Now it's always "<app_name> Setup.exe". But every time I need to rename it by removing spaces (on our storage space in names don't work very well...) and adding the version number to the end to identify the app version... So if it'd be possible to automize this process giving a custom name to the exe file produced, it would be usefull!

Thank you!

**Comment by GedasGa** [comment]
It is possible to customise the `name` and `version` in the `{project_root}/config.xml`; however, it is not possible to change anything apart from that.

Everything is managed by the `electron-builder`, which uses its default pattern for package names. For example, on `macOS` the generated `dmg` package name looks like the following -`DemoApp-1.0.0.dmg`. However, different targets have different default package name patterns, for example, `zip`, has the following pattern - `${productName}-${version}-mac.zip`. Same applies to the `exe` target, `electron-builder` uses it's default default pattern - `${productName} Setup ${version}.exe`.

With that being said your app should still have version appended (if you have it set), but you cannot customise anything else at this point. We are working on it though! 

Meanwhile, you could create a script that renames packages for you.
