### ISSUE TITLE
Append target top-level key options

### ISSUE THREAD

**Issue by GedasGa** [apache/cordova-electron#74]
# Feature Request

## Motivation Behind Feature

Right now we only append a few options for `mac`, `linux` and `win` such as target, icon and etc. This limits the functionality and possibilities a user can leverage which `electron-builder` has.

## Feature Description

Allow users to append all possible options that are supported by `electron-builder`. As well as, allow to use the same syntax and structure as in `electron-builder` configuration.

**Comment by erisu** [comment]
Resolved in #76
