### ISSUE TITLE
Change of start page in config.xml not working for electron platform

### ISSUE THREAD

**Issue by J-Gann** [apache/cordova-electron#80]
# Bug Report

## Problem
Changing the path of the index.html has no effect. For example changing
`<content src="index.html" />`
to
`<content src="index2.html" />`
still starts the original index.html although index2.html is in the folder besides index.html.
### What is expected to happen?
When starting the application for the platform electron, the index2.html file should be displayed.
### What does actually happen?
When starting the application for the platform electron, the displayed html file is not index2.html but the default index.html instead.

### Command or Code

Template cordova project, created by running `cordova create testProject`, then creating f.e. a file called index2.html next to the index.html, then changing the content path in config.xml to `<content src="index2.html" />`

### Environment, Platform, Device

Developing on windows for the electron platform

**Comment by Teddy95** [comment]
Same problem.
Tested with versions:
- 1.1.1
- 1.2.0-nightly.2019.11.15.d758a46e
- 2.0.0-nightly.2019.12.17.61f4d0f6
