### ISSUE TITLE
On Win8.1(probably the same on Win10), in 'List' Layout, see the default icon instead of mine.

### ISSUE THREAD

**Issue by scris** [apache/cordova-electron#82]
# Bug Report

## Problem
I switched into `1.1.0` ,made `icon.png` `icon@1.5x.png` `icon@2x.png` and `icon@4x.png` all set in config.xml and the res/electron folder, than build for windows on my computer that runs `MacOS 10.14`. 
However when I use win8.1 and turn the layout style into `List`, it turned back into default icon. Is it an issue, or maybe I did sth wrong? (I would assume you will get the same result on Win10)

### What is expected to happen?
In all of layout styles, will find custom icon.

### What does actually happen?
On Win8.1, In `Large Icons` layout style, it's all OK.
But for some reasons, I changed into `List` style and it began to show the default icon.(also on `Details` and `Tiles`)
On MacOS 10.14 everything is OK and just perfect.

## Information

`icon.png` `icon@1.5x.png` `icon@2x.png` and `icon@4x.png` are all set in config.xml and the res/electron folder

### Command or Code

command 
``` bash
MyMac:app we$ cordova build electron
  • electron-builder version=20.44.4
  • writing effective config file=platforms/electron/build/builder-effective-config.yaml
  • installing production dependencies platform=darwin arch=x64 appDir=/Users/we/Documents/GitHub/mydir/app/platforms/electron/www
  • packaging       platform=darwin arch=x64 electron=4.0.1 appOutDir=platforms/electron/build/mac
  • skipped macOS application code signing reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing allIdentities=
                                               1) XXX
                                               2) XXX
                                                  2 identities found
                                             
                                               Valid identities only
                                                  0 valid identities found
  • building        target=DMG arch=x64 file=platforms/electron/build/MyName-1.0.0.dmg
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=4.0.1 appOutDir=platforms/electron/build/win-unpacked
  • building        target=zip arch=x64 file=platforms/electron/build/MyName-1.0.0-win.zip
  • building block map blockMapFile=platforms/electron/build/MyName-1.0.0.dmg.blockmap

```
build.json
``` json
{
    "electron": {
        "mac": {
            "package": [ "dmg" ],
            "arch": [ "x64" ]
        },"windows": {
            "package": [ "zip" ],
            "arch": [ "x64" ]
        }
    }
}
```
config.xml
``` xml
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.mycompany.myname" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>MyName</name>
    <description>
        MyDesc
    </description>
    <author email="mymail@mymail.com" href="http://mysite.com">
        Author
    </author>
    <content src="index.html" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <platform name="electron">
        <icon src="res/electron/icon.png" />
        <icon src="res/electron/icon@1.5x.png" />
        <icon src="res/electron/icon@2x.png" />
        <icon src="res/electron/icon@4x.png" />
        <icon src="res/electron/icon@2x.png" target="installer" />
        <preference name="ElectronSettingsFilePath" value="res/electron/settings.json" />
    </platform>
</widget>
```

### Environment, Platform, Device

Node 10.16.0
Cordova 9.0.0 (cordova-lib@9.0.1)
cordova-electron 1.1.0
Building Computer: MacOS 10.14 Mojave
Testing Computer: Win 8.1

### Version information

See Above.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

Thanks a lot.

**Comment by GedasGa** [comment]
Thanks for throughout description. If I understood correctly, you're talking about different folder Views/Layouts, right? 

Anyhow, I've tested on Windows 10 using your provided configuration, but could not recreate this issue. 

Below you can see an unpacked `.zip` package and a custom icon displayed in `Details` layout view on Windows 10:

![Application Icon with `Details` layout view on Windows 10](https://user-images.githubusercontent.com/18717889/60709294-0a8eb900-9f4b-11e9-927c-29ebdf95bbc0.png)


What icon sizes are you using? Could try it on Windows 10 and see if you can recreate.

**Comment by scris** [comment]
@GedasGa Sorry for taken up your time. It's all of the `icon cache`. I rebuilt the icon cache and things were all OK.Thank you for your enthusiasm.

**Comment by janpio** [comment]
Can you share what command you used to reset that "Icon Cache"? (Didn't even know this was a thing)

**Comment by scris** [comment]
@janpio From a web article I learnt that just turn into a different theme(For Example: High Constract #1, at least I choose to turn to it), then turn back. It seems that it is a way.
