### ISSUE TITLE
When installing a local plugin in a cordova application, the building for the platform electron shows errors

### ISSUE THREAD

**Issue by J-Gann** [apache/cordova-electron#83]
# Bug Report

## Problem
When a local plugin is added to a cordova application by using `cordova plugin add ..\my-plugin\` the building of the application for the electron platform 'succeeds' with the following error:

773 verbose stack Error: ENOENT: no such file or directory, open 'C:\Users\Jonas\Documents\test\proj\platforms\electron\my-plugin\package.json'
774 verbose cwd C:\Users\Jonas\Documents\test\proj\platforms\electron\www
775 verbose Windows_NT 10.0.18362
776 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production" "--cache-min" "999999999"
777 verbose node v10.16.0
778 verbose npm  v6.9.0
779 error code ENOLOCAL
780 error Could not install from "..\my-plugin" as it does not contain a package.json file.

Here the full log: [2019-07-07T16_07_02_974Z-debug.log](https://github.com/apache/cordova-electron/files/3365883/2019-07-07T16_07_02_974Z-debug.log)

It seems like the package.json is not found because it is searched for in the wrong folder. Instead of \electron\my-plugin\package.json the plugin is located in \electron\www\plugins\my-plugin\package.json. 

### What is expected to happen?
The build process should not show an error because a package.json is there

### What does actually happen?
The build process shows an error that the package.json cant be found

## Information
The plugin is added and works fine (as far as i can see), but the error message is still there. This error does not occur on other platforms f.e. Android.

### Command or Code
Creating standard cordova application with `cordova create proj` and standard plugin created by `plugman create --name my-plugin --plugin_id my-plugin-jssoft --plugin_version 0.0.1` then adding the plugin using `cordova plugin add ..\my-plugin\`

### Environment, Platform, Device
Windows

**Comment by frank-dspeed** [comment]
@J-Gann please try with a absolute plugin path i think i see the failure there.

**Comment by xiaodeji** [comment]
I fixed, package.json    file:myplugin ->    file:../../../myplugin

**Comment by frank-dspeed** [comment]
@J-Gann please close this issue if its solved for you
cc @xiaodeji
