### ISSUE TITLE
Files from www not included when building for electron on OS X.

### ISSUE THREAD

**Issue by aleph1** [apache/cordova-electron#95]
# Bug Report
When building electron on OS X none of the files from www are being copied into the application package.

## Problem
When running "cordova run electron --nobuild" or "cordova run electron" everything works fine, but the electron application is referencing files that are outside of the application package. For example if I view the URL for the main index.html file it points here:

file:///Users/username/Development/projectname/platforms/electron/www/index.html

When I run "cordova build electron --release" then launch the .app file none of the assets are loaded, and if I right-click on the .app file and "Show Package Contents" none of the files from "www" are anywhere to be found within the package.

### What is expected to happen?
Seemingly, the entire contents of the "www" directory should be copied into the application package.

### What does actually happen?
As described above, none of the contents of the "www" directory end up in the application package.

### Environment, Platform, Device
OS X 10.14.6

### Version information
cordova 9.0.0 (cordova-lib@9.0.1)

platforms:
electron 1.1.1
ios 5.0.1

plugins:
cordova-plugin-console 1.1.0
cordova-plugin-device 2.0.3
cordova-plugin-file 6.0.2
cordova-plugin-media 5.0.3
cordova-plugin-splashscreen 5.0.3
cordova-plugin-whitelist 1.3.4

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by erisu** [comment]
When you run `cordova run electron`, this is spawning an Electron process and points: `file:///private/tmp/projectname/platforms/electron/www/`.

The run command does not use a built application, even if you did not pass in `--nobuild`.

If you run the built version of the application (`.app`), the path will become:  `file:///private/tmp/projectname.app/Contents/Resources/app.asar/`  

As shown, the path is inside the app file.

As for the assets in the build application, they are in the Package Contents but bundled inside an `asar` file.  

Example path to the `asar` file: `projectname.app/Contents/Resources/app.asar`
